# pod patch vault annotations yaml
spec:
  template:
    spec:
      serviceAccountName: vault-auth
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "example"
        vault.hashicorp.com/namespace: "default"
        vault.hashicorp.com/agent-inject-secret-kv: "nginx/secret"
        vault.hashicorp.com/agent-inject-secret-kv.json: "nginx/secret"
        vault.hashicorp.com/agent-inject-template-kv.json: |
          {{- with secret "nginx/secret" -}}
          {{ .Data.data | toJSONPretty }}
          {{- end }}